#!/bin/sh
set -e
# echo an error message before exiting
trap 'echo "\"${last_command}\" command filed with exit code $?."' EXIT


wasm_ext=".wasm"
project_name=canvas_page
project_name_bg=canvas_page_bg
bin_dir=./target/wasm32-unknown-unknown/release
www_dir=./www
server_dir=/var/www/html/wasm

cargo build --target wasm32-unknown-unknown --release
wasm-bindgen --target web --no-typescript --out-dir $bin_dir $bin_dir/$project_name$wasm_ext

wasm-gc $bin_dir/$project_name_bg$wasm_ext

#echo $bin_dir$project_name$wasm_ext
cp $bin_dir/$project_name_bg$wasm_ext $www_dir
cp $bin_dir/$project_name.js $www_dir

sudo cp $www_dir/* $server_dir